image: gitpod/workspace-java-17
tasks:
  - init: set mail
    command: git config --global user.email 14069652+lizzyTheLizard@users.noreply.github.com 
  - init: mvn package
    command: mvn exec:java
ports:
  - port: 3000
    onOpen: open-preview
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-maven
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
